services:
  - type: web
    name: printapp
    runtime: image
    image: 
      url: docker.io/sdec2000/printapp:latest
    envVars:
      - key: QUEUE_NAME
        value: TestQueue
      - key: EXCHANGE
        value: TestExchange
      - key: ROUTING_KEY
        value: fss
      - key: RABBITMQ_URL
        value: amqps://sdpwqges:GoybPFCeHCxMjtk0eqSeAhEykG335zGL@puffin.rmq2.cloudamqp.com/sdpwqges
      - key: RABBITMQ_USERNAME
        value: sdpwqges
      - key: RABBITMQ_PASSWORD
        value: GoybPFCeHCxMjtk0eqSeAhEykG335zGL
        
      # QUEUE_NAME: TestQueue
      # EXCHANGE: TestExchange
      # ROUTING_KEY: fss
      # RABBITMQ_URL: amqps://sdpwqges:GoybPFCeHCxMjtk0eqSeAhEykG335zGL@puffin.rmq2.cloudamqp.com/sdpwqges
      # RABBITMQ_USERNAME: sdpwqges
      # RABBITMQ_PASSWORD: GoybPFCeHCxMjtk0eqSeAhEykG335zGL
   
