name: PrintApp Render Deployment

on:
  push:
    branches:
      - main


jobs:
  deploy-app:
    runs-on: ubuntu-latest

    steps:
      - name: Render Deployment Trigerred
        run: curl ${{secrets.RENDER_DEPLOY_HOOK}}