name: PrintApp Render Deployment

on:
  push:
    branches:
      - main


jobs:
  deploy-app:
    runs-on: ubuntu-latest

    steps:
      - name: Render Deployment Trigerred
        run: curl ${{secrets.RENDER_DEPLOY_HOOK}}  #Update the secret to https://api.render.com/deploy/srv-cjo29sb6fquc73fheb40?key=wOSkU35Y_9s