# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: PrintApp

on:
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 19
      uses: actions/setup-java@v3
      with:
        java-version: '19'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      env:
          QUEUE_NAME: TestQueue
          EXCHANGE: TestExchange
          ROUTING_KEY: fss
          RABBITMQ_URL: amqps://sdpwqges:GoybPFCeHCxMjtk0eqSeAhEykG335zGL@puffin.rmq2.cloudamqp.com/sdpwqges
          RABBITMQ_USERNAME: sdpwqges
          RABBITMQ_PASSWORD: GoybPFCeHCxMjtk0eqSeAhEykG335zGL
      run: mvn clean package
    - name: Build & push Docker Image
      uses: mr-smithers-excellent/docker-build-push@v5
      with:
        image: sdec2000/printapp
        tags: latest
        registry: docker.io
        dockerfile: Dockerfile
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

